# pi05polaris-droid+toys300vae35ktdfsim-jointpos-stream
model:
  type: pi0
  action_horizon: 15
  max_token_len: 200
  pi05: true
  discrete_state_input: true
weight_loader:
  type: checkpoint
  params_path: gs://openpi-assets/checkpoints/polaris/pi05_droid_jointpos_polaris/params
data:
  type: lerobot_droid
  repo_id:
  - lerobot/droid_1.0.1
  - SamratSahoo/toys300_vae35k_tdf_sim
  assets:
    assets_dir: gs://openpi-assets/checkpoints/polaris/pi05_droid_jointpos_polaris/assets
    asset_id: droid
  base_config:
    prompt_from_task: true
  streaming: true
  nonidle_filter_paths:
    lerobot/droid_1.0.1: filters/lerobot_droid_1.0.1.json
  joint_position_actions: true
  sampling_weights:
    lerobot/droid_1.0.1: 0.5
    SamratSahoo/toys300_vae35k_tdf_sim: 0.5
num_train_steps: 20000
save_interval: 20000
