# pi05_aloha_pen_uncap
model:
  type: pi0
  max_token_len: 200
  pi05: true
  discrete_state_input: true
weight_loader:
  type: checkpoint
  params_path: gs://openpi-assets/checkpoints/pi05_base/params
data:
  type: lerobot_aloha
  repo_id: physical-intelligence/aloha_pen_uncap_diverse
  assets:
    assets_dir: gs://openpi-assets/checkpoints/pi05_base/assets
    asset_id: trossen
  default_prompt: uncap the pen
  repack_transforms:
    inputs:
    - type: repack
      structure:
        images:
          cam_high: observation.images.cam_high
          cam_left_wrist: observation.images.cam_left_wrist
          cam_right_wrist: observation.images.cam_right_wrist
        state: observation.state
        actions: action
batch_size: 64
num_train_steps: 20000
