# paligemma_vq_droid
model:
  type: pi0_fast
  action_dim: 8
  action_horizon: 15
  fast_model_tokenizer: fsq_tokenizer
  fast_model_tokenizer_kwargs:
    fsq_tokenizer_path: gs://openpi-assets/tokenizers/droid_fsq_tokenizer
data:
  type: simple
  assets:
    asset_id: droid
  base_config:
    prompt_from_task: true
  data_transforms:
    inputs:
    - type: droid_inputs
      model_type: PI0_FAST
    outputs:
    - type: droid_outputs
